### ISSUE TITLE
Issue with using API in PlayerJoinEvent

### ISSUE THREAD

**Issue by Simo389** [sgtcaze/NametagEdit#19]
So prior to 1.8 I've used the API to set player name colours:
NametagAPI.updateNametagHard(player.getName(), "§a", "");

But if I now use this in the PlayerJoinEvent, it has no effect. I have to put it on a 1 tick delay to get it working. I'm assuming this is a bug, so I thought was worth reporting.

**Comment by Simo389** [comment]
Just a heads up, this is still an issue. I just tried removing the 1 tick delay and the API doesn't set the colour correctly.

**Comment by sgtcaze** [comment]
Hmm, ok thank you. Had 4 commits recently I thought the issue was solved. Will fix it in the next commit.

**Comment by sgtcaze** [comment]
Should be good now.

**Comment by Simo389** [comment]
@sgtcaze Don't suppose you can run that latest fix on your build server. :-)

**Comment by sgtcaze** [comment]
Ah forgot my Jenkins doesn't have an auto build script. Here you go http://ci.playmc.cc/job/NametagEdit/4/

**Comment by Simo389** [comment]
@sgtcaze Sorry to have to bring this up again, but I think this still isn't fixed. Using the same code as above without a 1 tick delay, players' name colours aren't being set on the tab list.

**Comment by sgtcaze** [comment]
They actually are. 1.8.1 clients cannot see the tags in the tab on 1.8 protocol hack servers. 1.8.0 clients can, however. Running a 1.8 non protocol hack shows the tags no problem.
